### ISSUE TITLE
updated package doesn't contain fixes

### ISSUE THREAD

**Issue by dromer** [taylordotfish/markov.lua#3]
So .. this took me a while to find out because I only did a full update of my project today (and I think until now I still had the manual fix in it), but apparently the package on luarocks doesn't actually contain the `0.1-1` code!

I just installed it locally and `markov.lua` clearly still says: `version = "0.1-0",`

**Comment by taylordotfish** [comment]
Should be fixed now in version 0.1-3. I didn't realize `luarocks pack` and `luarocks upload` were re-cloning the repository every time, and I had been uploading before pushing to the repository.

**Comment by dromer** [comment]
Yes! thnx :D
